name: tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '23 3 * * *'

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # extensions: mbstring, zip
          # coverage: none

      - name: composer install --prefer-dist --no-interaction
        run: composer install --prefer-dist --no-interaction

      - name: composer analyse
        run: composer analyse

      - name: composer test
        run: composer test
